version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: chatbot-sqlserver
    hostname: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "ChatBot123!"
      MSSQL_PID: Express
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - chatbot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'ChatBot123!' -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  adminer:
    image: adminer:4.8.1
    container_name: chatbot-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: sqlserver
    networks:
      - chatbot-network
    restart: unless-stopped
    depends_on:
      - sqlserver

volumes:
  sqlserver_data:
    driver: local

networks:
  chatbot-network:
    driver: bridge